FROM golang:1.18

RUN apt-get update && apt-get install sqlite3 && apt-get clean
WORKDIR /go/src/panopticon

COPY ./runtests.sh /go/src/panopticon
COPY ./tests /go/src/panopticon/tests
COPY ./*.go /go/src/panopticon
COPY ./go.mod /go/src/panopticon
COPY ./go.sum /go/src/panopticon
RUN go build
CMD ./runtests.sh
