# GitHub actions workflow which builds and publishes the docker images.

name: Build and push docker images (Panopticon-aggregate)

on:
  push:
    tags: ["v*"]
  pull_request:
    paths:
      - 'Dockerfile-aggregate'
      - '.github/workflows/docker_aggregate.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: docker buildx inspect

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        # we only push if this is a release, so don't need to log in any other
        # time.
        if: "${{ startsWith(github.ref, 'refs/tags/v') }}"
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Calculate docker image tags
        id: set-tag
        uses: docker/metadata-action@v3
        with:
          images: matrixdotorg/panopticon
          tags: |
            type=ref,event=tag,prefix=aggregation-release-
          # we want all tags to be prefixed with aggregate- (to distinguish from
          # actual Panopticon images). This INCLUDES 'latest' tags.
          # N.B. this is overridden by the prefixes specified in the tags section
          flavor: |
            prefix=aggregation-,onlatest=true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push all platforms
        uses: docker/build-push-action@v2
        with:
          context: .
          # only push if this is a release (this evaluates to true or false)
          push: "${{ startsWith(github.ref, 'refs/tags/v') }}"
          labels: "gitsha1=${{ github.sha }}"
          tags: "${{ steps.set-tag.outputs.tags }}"
          file: "Dockerfile-aggregate"
          platforms: linux/amd64,linux/arm64
